name: Deploy Task 1

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r TASK1/requirements.txt

      - name: Deploy to Streamlit Cloud
        run: |
          streamlit deploy TASK1/chatgptchatbot.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
